trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


jobs:
- job: TerraformOnMultipleSubscriptions
  steps:
  - checkout: self
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1

    inputs:
      terraformVersion: '0.14.0'

  - template: template/template.yaml
    parameters:
      azureServiceConnection: 'practice-connection'
