jobs:
  - job: TerraformOnMultipleSubscriptions
    steps:
      - checkout: self
      - inputs:
          terraformVersion: 0.14.0
        task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      - displayName: Terraform Init
        script: |
          
          terraform init
      - displayName: Terraform Plan
        script: |
          
          terraform plan
      - condition: eq(parameters.tfAction, 'apply')
        displayName: Terraform Apply
        script: |
          
          terraform apply -auto-approve
      - condition: eq(parameters.tfAction, 'destroy')
        displayName: Terraform Destroy
        script: |
          
          terraform destroy -auto-approve
pool:
  vmImage: ubuntu-latest
trigger:
  - main
  - parameters:
      azureServiceConnection: practice connection 1
    template: template/template.yaml
  - default: apply
    displayName: Terraform Action
    name: tfAction
    type: string
    values:
      - apply
      - destroy
