trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


jobs:
- job: TerraformOnMultipleSubscriptions
  steps:
  - checkout: self
  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1

    inputs:
      terraformVersion: '0.14.0'

  - template: template/template.yaml
    parameters:
      azureServiceConnection: 'practice-connection'
