trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TerraformOnMultipleSubscriptions
  steps:
  - checkout: self
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '0.14.0'

  - template: terraform-steps-template.yml
    parameters:
      azureServiceConnection: 'testconnection'