trigger:

- main

 

parameters:

- name: tfAction

  displayName: Terraform Action

  type: string

  default: apply

  values:

  - apply

  - destroy

 

pool:

  vmImage: 'ubuntu-latest'

 

jobs:

- job: TerraformOnMultipleSubscriptions

  steps:

  - checkout: self

 

  - task: TerraformInstaller@0

    inputs:

      terraformVersion: '0.14.0'

 

  - script: |

      terraform init

    displayName: 'Terraform Init'

 

  - script: |

      terraform plan

    displayName: 'Terraform Plan'

    

  - script: |

      terraform apply -auto-approve

    displayName: 'Terraform Apply'

    condition: eq(parameters.tfAction, 'apply')

 

  - script: |

      terraform destroy -auto-approve

    displayName: 'Terraform Destroy'

    condition: eq(parameters.tfAction, 'destroy')

 

  - template: template/template.yaml

    parameters:

      azureServiceConnection: 'practice-connection'